In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])

In [4]:
print(a, type(a))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [5]:
print(a.shape)

(5,)


In [6]:
a[-1:]

array([5])

In [8]:
a[-1:3]

array([], dtype=int32)

In [9]:
a[::-1]

array([5, 4, 3, 2, 1])

In [10]:
print(a + 5)

[ 6  7  8  9 10]


In [22]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [24]:
print(b, type(b))
b

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] <class 'numpy.ndarray'>


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
print(b.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [26]:
b.nbytes

48

In [27]:
b.shape

(3, 4)

In [37]:
row_r1 = b[:2, :3]
row_r1

array([[1, 2, 3],
       [5, 6, 7]])

In [38]:
row_r2= b[1,:]
row_r2

array([5, 6, 7, 8])

In [41]:
#1 аргумент - строки, 2-й - колонки

In [39]:
row_r1.base

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[[1 2 3]
 [5 6 7]] (2, 3)
[5 6 7 8] (4,)


In [45]:
col_r1 = b[:, 1]
print(col_r1, '\n---\n', col_r1.shape)

[ 2  6 10] 
---
 (3,)


In [46]:
col_r2 = b[:, 1:3]
print(col_r2, '\n---\n', col_r2.shape)

[[ 2  3]
 [ 6  7]
 [10 11]] 
---
 (3, 2)
